### ISSUE TITLE
RuntimeError: size of dimension does not match previous size, operand 1, dim 1

### ISSUE THREAD

**Issue by tom1997** [conradry/max-deeplab#5]
In block file
qr = torch.einsum('bnci,cij->bnij', q, qemb) line 173, in forward

How can I solve this error?

**Comment by conradry** [comment]
What's the error?

**Comment by tom1997** [comment]
Yes,the code is not running on example notebook. I try to move your code into mmlab-segmentation structure https://github.com/open-mmlab/mmsegmentation, and test it on voc12 dataset, and I just move backbone and block py file. This error occurs in backbone layer3
After debugging q and qemb shape, they are torch.Size([256, 8, 16, 64]) torch.Size([16, 80, 80]), that's why this error report
Should I reproduce model file in this structure?Because I am now using encoder-decoder given by mmlab.

**Comment by conradry** [comment]
I don't know enough about mmsegmentation to help with that specific problem. But yes, you probably need to reproduce the model file.

**Comment by lxa9867** [comment]
> Yes,the code is not running on example notebook. I try to move your code into mmlab-segmentation structure https://github.com/open-mmlab/mmsegmentation, and test it on voc12 dataset, and I just move backbone,block and loss py file. This error occurs in backbone layer3
> After debugging q and qemb shape, they are torch.Size([256, 8, 16, 64]) torch.Size([16, 80, 80]), that's why this error report
> Should I reproduce model file in this structure?Because I am now using encoder-decoder given by mmlab.

Hello, I am also reproducing results of MaX-Deeplab while got stuck for weeks. My MaX-S only yield a 50 training Dice and 20 PQ on val set. Have you reproducing the results claimed in Paper? Thank you.
